version: "3.8"

services:
  db:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j/data:/data
